vich_uploader:
    db_driver: orm

    mappings:
        default_media_object:
            uri_prefix:         '%directory_media%'
            upload_destination: '%kernel.project_dir%/public%directory_media%'
            # namer: Vich\UploaderBundle\Naming\SmartUniqueNamer