# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: project.yaml }
    
parameters:
    locale: fr_FR
    sylius_installer_currency: EUR
    directory_image_media_object: /media/image
    directory_document_media_object: /media/document
    directory_icon_media_object: /media/icon
    directory_cache_prefix: media/cache/resolve
    path_directory_media: '%kernel.project_dir%/public/media/image'
    developers: [ 'johan.remy@graines-digitales.online' ]
    sendinblue_api_key: '%env(resolve:SENDINBLUE_API_KEY)%'
    sendinblue_list_newsletter_id: '%env(resolve:SENDINBLUE_LIST_NEWSLETTER_ID)%'

    
    

       